#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace store_api_test.DataMapping
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="znode_multifront")]
	public partial class CategoryDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertZNodeCategory(ZNodeCategory instance);
    partial void UpdateZNodeCategory(ZNodeCategory instance);
    partial void DeleteZNodeCategory(ZNodeCategory instance);
    #endregion
		
		public CategoryDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["znode_multifrontConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public CategoryDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CategoryDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CategoryDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CategoryDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ZNodeCategory> ZNodeCategories
		{
			get
			{
				return this.GetTable<ZNodeCategory>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ZNodeCategory")]
	public partial class ZNodeCategory : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CategoryID;
		
		private string _Name;
		
		private string _Title;
		
		private string _ShortDescription;
		
		private string _Description;
		
		private string _ImageFile;
		
		private string _ImageAltTag;
		
		private bool _VisibleInd;
		
		private bool _SubCategoryGridVisibleInd;
		
		private string _SEOTitle;
		
		private string _SEOKeywords;
		
		private string _SEODescription;
		
		private string _AlternateDescription;
		
		private System.Nullable<int> _DisplayOrder;
		
		private string _Custom1;
		
		private string _Custom2;
		
		private string _Custom3;
		
		private string _SEOURL;
		
		private System.Nullable<int> _PortalID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCategoryIDChanging(int value);
    partial void OnCategoryIDChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnTitleChanging(string value);
    partial void OnTitleChanged();
    partial void OnShortDescriptionChanging(string value);
    partial void OnShortDescriptionChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnImageFileChanging(string value);
    partial void OnImageFileChanged();
    partial void OnImageAltTagChanging(string value);
    partial void OnImageAltTagChanged();
    partial void OnVisibleIndChanging(bool value);
    partial void OnVisibleIndChanged();
    partial void OnSubCategoryGridVisibleIndChanging(bool value);
    partial void OnSubCategoryGridVisibleIndChanged();
    partial void OnSEOTitleChanging(string value);
    partial void OnSEOTitleChanged();
    partial void OnSEOKeywordsChanging(string value);
    partial void OnSEOKeywordsChanged();
    partial void OnSEODescriptionChanging(string value);
    partial void OnSEODescriptionChanged();
    partial void OnAlternateDescriptionChanging(string value);
    partial void OnAlternateDescriptionChanged();
    partial void OnDisplayOrderChanging(System.Nullable<int> value);
    partial void OnDisplayOrderChanged();
    partial void OnCustom1Changing(string value);
    partial void OnCustom1Changed();
    partial void OnCustom2Changing(string value);
    partial void OnCustom2Changed();
    partial void OnCustom3Changing(string value);
    partial void OnCustom3Changed();
    partial void OnSEOURLChanging(string value);
    partial void OnSEOURLChanged();
    partial void OnPortalIDChanging(System.Nullable<int> value);
    partial void OnPortalIDChanged();
    #endregion
		
		public ZNodeCategory()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoryID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CategoryID
		{
			get
			{
				return this._CategoryID;
			}
			set
			{
				if ((this._CategoryID != value))
				{
					this.OnCategoryIDChanging(value);
					this.SendPropertyChanging();
					this._CategoryID = value;
					this.SendPropertyChanged("CategoryID");
					this.OnCategoryIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="NVarChar(MAX)")]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this.OnTitleChanging(value);
					this.SendPropertyChanging();
					this._Title = value;
					this.SendPropertyChanged("Title");
					this.OnTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShortDescription", DbType="NVarChar(MAX)")]
		public string ShortDescription
		{
			get
			{
				return this._ShortDescription;
			}
			set
			{
				if ((this._ShortDescription != value))
				{
					this.OnShortDescriptionChanging(value);
					this.SendPropertyChanging();
					this._ShortDescription = value;
					this.SendPropertyChanged("ShortDescription");
					this.OnShortDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(MAX)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ImageFile", DbType="NVarChar(MAX)")]
		public string ImageFile
		{
			get
			{
				return this._ImageFile;
			}
			set
			{
				if ((this._ImageFile != value))
				{
					this.OnImageFileChanging(value);
					this.SendPropertyChanging();
					this._ImageFile = value;
					this.SendPropertyChanged("ImageFile");
					this.OnImageFileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ImageAltTag", DbType="NVarChar(MAX)")]
		public string ImageAltTag
		{
			get
			{
				return this._ImageAltTag;
			}
			set
			{
				if ((this._ImageAltTag != value))
				{
					this.OnImageAltTagChanging(value);
					this.SendPropertyChanging();
					this._ImageAltTag = value;
					this.SendPropertyChanged("ImageAltTag");
					this.OnImageAltTagChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VisibleInd", DbType="Bit NOT NULL")]
		public bool VisibleInd
		{
			get
			{
				return this._VisibleInd;
			}
			set
			{
				if ((this._VisibleInd != value))
				{
					this.OnVisibleIndChanging(value);
					this.SendPropertyChanging();
					this._VisibleInd = value;
					this.SendPropertyChanged("VisibleInd");
					this.OnVisibleIndChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubCategoryGridVisibleInd", DbType="Bit NOT NULL")]
		public bool SubCategoryGridVisibleInd
		{
			get
			{
				return this._SubCategoryGridVisibleInd;
			}
			set
			{
				if ((this._SubCategoryGridVisibleInd != value))
				{
					this.OnSubCategoryGridVisibleIndChanging(value);
					this.SendPropertyChanging();
					this._SubCategoryGridVisibleInd = value;
					this.SendPropertyChanged("SubCategoryGridVisibleInd");
					this.OnSubCategoryGridVisibleIndChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SEOTitle", DbType="NVarChar(MAX)")]
		public string SEOTitle
		{
			get
			{
				return this._SEOTitle;
			}
			set
			{
				if ((this._SEOTitle != value))
				{
					this.OnSEOTitleChanging(value);
					this.SendPropertyChanging();
					this._SEOTitle = value;
					this.SendPropertyChanged("SEOTitle");
					this.OnSEOTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SEOKeywords", DbType="NVarChar(MAX)")]
		public string SEOKeywords
		{
			get
			{
				return this._SEOKeywords;
			}
			set
			{
				if ((this._SEOKeywords != value))
				{
					this.OnSEOKeywordsChanging(value);
					this.SendPropertyChanging();
					this._SEOKeywords = value;
					this.SendPropertyChanged("SEOKeywords");
					this.OnSEOKeywordsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SEODescription", DbType="NVarChar(MAX)")]
		public string SEODescription
		{
			get
			{
				return this._SEODescription;
			}
			set
			{
				if ((this._SEODescription != value))
				{
					this.OnSEODescriptionChanging(value);
					this.SendPropertyChanging();
					this._SEODescription = value;
					this.SendPropertyChanged("SEODescription");
					this.OnSEODescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AlternateDescription", DbType="NVarChar(MAX)")]
		public string AlternateDescription
		{
			get
			{
				return this._AlternateDescription;
			}
			set
			{
				if ((this._AlternateDescription != value))
				{
					this.OnAlternateDescriptionChanging(value);
					this.SendPropertyChanging();
					this._AlternateDescription = value;
					this.SendPropertyChanged("AlternateDescription");
					this.OnAlternateDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DisplayOrder", DbType="Int")]
		public System.Nullable<int> DisplayOrder
		{
			get
			{
				return this._DisplayOrder;
			}
			set
			{
				if ((this._DisplayOrder != value))
				{
					this.OnDisplayOrderChanging(value);
					this.SendPropertyChanging();
					this._DisplayOrder = value;
					this.SendPropertyChanged("DisplayOrder");
					this.OnDisplayOrderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Custom1", DbType="NVarChar(MAX)")]
		public string Custom1
		{
			get
			{
				return this._Custom1;
			}
			set
			{
				if ((this._Custom1 != value))
				{
					this.OnCustom1Changing(value);
					this.SendPropertyChanging();
					this._Custom1 = value;
					this.SendPropertyChanged("Custom1");
					this.OnCustom1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Custom2", DbType="NVarChar(MAX)")]
		public string Custom2
		{
			get
			{
				return this._Custom2;
			}
			set
			{
				if ((this._Custom2 != value))
				{
					this.OnCustom2Changing(value);
					this.SendPropertyChanging();
					this._Custom2 = value;
					this.SendPropertyChanged("Custom2");
					this.OnCustom2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Custom3", DbType="NVarChar(MAX)")]
		public string Custom3
		{
			get
			{
				return this._Custom3;
			}
			set
			{
				if ((this._Custom3 != value))
				{
					this.OnCustom3Changing(value);
					this.SendPropertyChanging();
					this._Custom3 = value;
					this.SendPropertyChanged("Custom3");
					this.OnCustom3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SEOURL", DbType="NVarChar(100)")]
		public string SEOURL
		{
			get
			{
				return this._SEOURL;
			}
			set
			{
				if ((this._SEOURL != value))
				{
					this.OnSEOURLChanging(value);
					this.SendPropertyChanging();
					this._SEOURL = value;
					this.SendPropertyChanged("SEOURL");
					this.OnSEOURLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PortalID", DbType="Int")]
		public System.Nullable<int> PortalID
		{
			get
			{
				return this._PortalID;
			}
			set
			{
				if ((this._PortalID != value))
				{
					this.OnPortalIDChanging(value);
					this.SendPropertyChanging();
					this._PortalID = value;
					this.SendPropertyChanged("PortalID");
					this.OnPortalIDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
