#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace store_api_test.DataMapping
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="znode_multifront")]
	public partial class PortalDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertZNodePortal(ZNodePortal instance);
    partial void UpdateZNodePortal(ZNodePortal instance);
    partial void DeleteZNodePortal(ZNodePortal instance);
    #endregion
		
		public PortalDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["znode_multifrontConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public PortalDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PortalDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PortalDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PortalDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ZNodePortal> ZNodePortals
		{
			get
			{
				return this.GetTable<ZNodePortal>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ZNodePortal")]
	public partial class ZNodePortal : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _PortalID;
		
		private string _CompanyName;
		
		private string _StoreName;
		
		private string _LogoPath;
		
		private bool _UseSSL;
		
		private string _AdminEmail;
		
		private string _SalesEmail;
		
		private string _CustomerServiceEmail;
		
		private string _SalesPhoneNumber;
		
		private string _CustomerServicePhoneNumber;
		
		private string _ImageNotAvailablePath;
		
		private byte _MaxCatalogDisplayColumns;
		
		private int _MaxCatalogDisplayItems;
		
		private int _MaxCatalogCategoryDisplayThumbnails;
		
		private int _MaxCatalogItemSmallThumbnailWidth;
		
		private int _MaxCatalogItemSmallWidth;
		
		private int _MaxCatalogItemMediumWidth;
		
		private int _MaxCatalogItemThumbnailWidth;
		
		private int _MaxCatalogItemLargeWidth;
		
		private int _MaxCatalogItemCrossSellWidth;
		
		private bool _ShowSwatchInCategory;
		
		private bool _ShowAlternateImageInCategory;
		
		private bool _ActiveInd;
		
		private string _SMTPServer;
		
		private string _SMTPUserName;
		
		private string _SMTPPassword;
		
		private System.Nullable<int> _SMTPPort;
		
		private string _SiteWideBottomJavascript;
		
		private string _SiteWideTopJavascript;
		
		private string _OrderReceiptAffiliateJavascript;
		
		private string _SiteWideAnalyticsJavascript;
		
		private string _GoogleAnalyticsCode;
		
		private string _UPSUserName;
		
		private string _UPSPassword;
		
		private string _UPSKey;
		
		private string _ShippingOriginZipCode;
		
		private string _MasterPage;
		
		private int _ShopByPriceMin;
		
		private int _ShopByPriceMax;
		
		private int _ShopByPriceIncrement;
		
		private string _FedExAccountNumber;
		
		private string _FedExMeterNumber;
		
		private string _FedExProductionKey;
		
		private string _FedExSecurityCode;
		
		private string _FedExCSPKey;
		
		private string _FedExCSPPassword;
		
		private string _FedExClientProductId;
		
		private string _FedExClientProductVersion;
		
		private string _FedExDropoffType;
		
		private string _FedExPackagingType;
		
		private System.Nullable<bool> _FedExUseDiscountRate;
		
		private System.Nullable<bool> _FedExAddInsurance;
		
		private string _ShippingOriginAddress1;
		
		private string _ShippingOriginAddress2;
		
		private string _ShippingOriginCity;
		
		private string _ShippingOriginStateCode;
		
		private string _ShippingOriginCountryCode;
		
		private string _ShippingOriginPhone;
		
		private System.Nullable<int> _CurrencyTypeID;
		
		private string _WeightUnit;
		
		private string _DimensionUnit;
		
		private string _EmailListLogin;
		
		private string _EmailListPassword;
		
		private string _EmailListDefaultList;
		
		private bool _ShippingTaxable;
		
		private System.Nullable<int> _DefaultOrderStateID;
		
		private string _DefaultReviewStatus;
		
		private System.Nullable<int> _DefaultAnonymousProfileID;
		
		private System.Nullable<int> _DefaultRegisteredProfileID;
		
		private bool _InclusiveTax;
		
		private string _SeoDefaultProductTitle;
		
		private string _SeoDefaultProductDescription;
		
		private string _SeoDefaultProductKeyword;
		
		private string _SeoDefaultCategoryTitle;
		
		private string _SeoDefaultCategoryDescription;
		
		private string _SeoDefaultCategoryKeyword;
		
		private string _SeoDefaultContentTitle;
		
		private string _SeoDefaultContentDescription;
		
		private string _SeoDefaultContentKeyword;
		
		private string _TimeZoneOffset;
		
		private int _LocaleID;
		
		private System.Nullable<int> _SplashCategoryID;
		
		private string _SplashImageFile;
		
		private string _MobileTheme;
		
		private System.Nullable<bool> _PersistentCartEnabled;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPortalIDChanging(int value);
    partial void OnPortalIDChanged();
    partial void OnCompanyNameChanging(string value);
    partial void OnCompanyNameChanged();
    partial void OnStoreNameChanging(string value);
    partial void OnStoreNameChanged();
    partial void OnLogoPathChanging(string value);
    partial void OnLogoPathChanged();
    partial void OnUseSSLChanging(bool value);
    partial void OnUseSSLChanged();
    partial void OnAdminEmailChanging(string value);
    partial void OnAdminEmailChanged();
    partial void OnSalesEmailChanging(string value);
    partial void OnSalesEmailChanged();
    partial void OnCustomerServiceEmailChanging(string value);
    partial void OnCustomerServiceEmailChanged();
    partial void OnSalesPhoneNumberChanging(string value);
    partial void OnSalesPhoneNumberChanged();
    partial void OnCustomerServicePhoneNumberChanging(string value);
    partial void OnCustomerServicePhoneNumberChanged();
    partial void OnImageNotAvailablePathChanging(string value);
    partial void OnImageNotAvailablePathChanged();
    partial void OnMaxCatalogDisplayColumnsChanging(byte value);
    partial void OnMaxCatalogDisplayColumnsChanged();
    partial void OnMaxCatalogDisplayItemsChanging(int value);
    partial void OnMaxCatalogDisplayItemsChanged();
    partial void OnMaxCatalogCategoryDisplayThumbnailsChanging(int value);
    partial void OnMaxCatalogCategoryDisplayThumbnailsChanged();
    partial void OnMaxCatalogItemSmallThumbnailWidthChanging(int value);
    partial void OnMaxCatalogItemSmallThumbnailWidthChanged();
    partial void OnMaxCatalogItemSmallWidthChanging(int value);
    partial void OnMaxCatalogItemSmallWidthChanged();
    partial void OnMaxCatalogItemMediumWidthChanging(int value);
    partial void OnMaxCatalogItemMediumWidthChanged();
    partial void OnMaxCatalogItemThumbnailWidthChanging(int value);
    partial void OnMaxCatalogItemThumbnailWidthChanged();
    partial void OnMaxCatalogItemLargeWidthChanging(int value);
    partial void OnMaxCatalogItemLargeWidthChanged();
    partial void OnMaxCatalogItemCrossSellWidthChanging(int value);
    partial void OnMaxCatalogItemCrossSellWidthChanged();
    partial void OnShowSwatchInCategoryChanging(bool value);
    partial void OnShowSwatchInCategoryChanged();
    partial void OnShowAlternateImageInCategoryChanging(bool value);
    partial void OnShowAlternateImageInCategoryChanged();
    partial void OnActiveIndChanging(bool value);
    partial void OnActiveIndChanged();
    partial void OnSMTPServerChanging(string value);
    partial void OnSMTPServerChanged();
    partial void OnSMTPUserNameChanging(string value);
    partial void OnSMTPUserNameChanged();
    partial void OnSMTPPasswordChanging(string value);
    partial void OnSMTPPasswordChanged();
    partial void OnSMTPPortChanging(System.Nullable<int> value);
    partial void OnSMTPPortChanged();
    partial void OnSiteWideBottomJavascriptChanging(string value);
    partial void OnSiteWideBottomJavascriptChanged();
    partial void OnSiteWideTopJavascriptChanging(string value);
    partial void OnSiteWideTopJavascriptChanged();
    partial void OnOrderReceiptAffiliateJavascriptChanging(string value);
    partial void OnOrderReceiptAffiliateJavascriptChanged();
    partial void OnSiteWideAnalyticsJavascriptChanging(string value);
    partial void OnSiteWideAnalyticsJavascriptChanged();
    partial void OnGoogleAnalyticsCodeChanging(string value);
    partial void OnGoogleAnalyticsCodeChanged();
    partial void OnUPSUserNameChanging(string value);
    partial void OnUPSUserNameChanged();
    partial void OnUPSPasswordChanging(string value);
    partial void OnUPSPasswordChanged();
    partial void OnUPSKeyChanging(string value);
    partial void OnUPSKeyChanged();
    partial void OnShippingOriginZipCodeChanging(string value);
    partial void OnShippingOriginZipCodeChanged();
    partial void OnMasterPageChanging(string value);
    partial void OnMasterPageChanged();
    partial void OnShopByPriceMinChanging(int value);
    partial void OnShopByPriceMinChanged();
    partial void OnShopByPriceMaxChanging(int value);
    partial void OnShopByPriceMaxChanged();
    partial void OnShopByPriceIncrementChanging(int value);
    partial void OnShopByPriceIncrementChanged();
    partial void OnFedExAccountNumberChanging(string value);
    partial void OnFedExAccountNumberChanged();
    partial void OnFedExMeterNumberChanging(string value);
    partial void OnFedExMeterNumberChanged();
    partial void OnFedExProductionKeyChanging(string value);
    partial void OnFedExProductionKeyChanged();
    partial void OnFedExSecurityCodeChanging(string value);
    partial void OnFedExSecurityCodeChanged();
    partial void OnFedExCSPKeyChanging(string value);
    partial void OnFedExCSPKeyChanged();
    partial void OnFedExCSPPasswordChanging(string value);
    partial void OnFedExCSPPasswordChanged();
    partial void OnFedExClientProductIdChanging(string value);
    partial void OnFedExClientProductIdChanged();
    partial void OnFedExClientProductVersionChanging(string value);
    partial void OnFedExClientProductVersionChanged();
    partial void OnFedExDropoffTypeChanging(string value);
    partial void OnFedExDropoffTypeChanged();
    partial void OnFedExPackagingTypeChanging(string value);
    partial void OnFedExPackagingTypeChanged();
    partial void OnFedExUseDiscountRateChanging(System.Nullable<bool> value);
    partial void OnFedExUseDiscountRateChanged();
    partial void OnFedExAddInsuranceChanging(System.Nullable<bool> value);
    partial void OnFedExAddInsuranceChanged();
    partial void OnShippingOriginAddress1Changing(string value);
    partial void OnShippingOriginAddress1Changed();
    partial void OnShippingOriginAddress2Changing(string value);
    partial void OnShippingOriginAddress2Changed();
    partial void OnShippingOriginCityChanging(string value);
    partial void OnShippingOriginCityChanged();
    partial void OnShippingOriginStateCodeChanging(string value);
    partial void OnShippingOriginStateCodeChanged();
    partial void OnShippingOriginCountryCodeChanging(string value);
    partial void OnShippingOriginCountryCodeChanged();
    partial void OnShippingOriginPhoneChanging(string value);
    partial void OnShippingOriginPhoneChanged();
    partial void OnCurrencyTypeIDChanging(System.Nullable<int> value);
    partial void OnCurrencyTypeIDChanged();
    partial void OnWeightUnitChanging(string value);
    partial void OnWeightUnitChanged();
    partial void OnDimensionUnitChanging(string value);
    partial void OnDimensionUnitChanged();
    partial void OnEmailListLoginChanging(string value);
    partial void OnEmailListLoginChanged();
    partial void OnEmailListPasswordChanging(string value);
    partial void OnEmailListPasswordChanged();
    partial void OnEmailListDefaultListChanging(string value);
    partial void OnEmailListDefaultListChanged();
    partial void OnShippingTaxableChanging(bool value);
    partial void OnShippingTaxableChanged();
    partial void OnDefaultOrderStateIDChanging(System.Nullable<int> value);
    partial void OnDefaultOrderStateIDChanged();
    partial void OnDefaultReviewStatusChanging(string value);
    partial void OnDefaultReviewStatusChanged();
    partial void OnDefaultAnonymousProfileIDChanging(System.Nullable<int> value);
    partial void OnDefaultAnonymousProfileIDChanged();
    partial void OnDefaultRegisteredProfileIDChanging(System.Nullable<int> value);
    partial void OnDefaultRegisteredProfileIDChanged();
    partial void OnInclusiveTaxChanging(bool value);
    partial void OnInclusiveTaxChanged();
    partial void OnSeoDefaultProductTitleChanging(string value);
    partial void OnSeoDefaultProductTitleChanged();
    partial void OnSeoDefaultProductDescriptionChanging(string value);
    partial void OnSeoDefaultProductDescriptionChanged();
    partial void OnSeoDefaultProductKeywordChanging(string value);
    partial void OnSeoDefaultProductKeywordChanged();
    partial void OnSeoDefaultCategoryTitleChanging(string value);
    partial void OnSeoDefaultCategoryTitleChanged();
    partial void OnSeoDefaultCategoryDescriptionChanging(string value);
    partial void OnSeoDefaultCategoryDescriptionChanged();
    partial void OnSeoDefaultCategoryKeywordChanging(string value);
    partial void OnSeoDefaultCategoryKeywordChanged();
    partial void OnSeoDefaultContentTitleChanging(string value);
    partial void OnSeoDefaultContentTitleChanged();
    partial void OnSeoDefaultContentDescriptionChanging(string value);
    partial void OnSeoDefaultContentDescriptionChanged();
    partial void OnSeoDefaultContentKeywordChanging(string value);
    partial void OnSeoDefaultContentKeywordChanged();
    partial void OnTimeZoneOffsetChanging(string value);
    partial void OnTimeZoneOffsetChanged();
    partial void OnLocaleIDChanging(int value);
    partial void OnLocaleIDChanged();
    partial void OnSplashCategoryIDChanging(System.Nullable<int> value);
    partial void OnSplashCategoryIDChanged();
    partial void OnSplashImageFileChanging(string value);
    partial void OnSplashImageFileChanged();
    partial void OnMobileThemeChanging(string value);
    partial void OnMobileThemeChanged();
    partial void OnPersistentCartEnabledChanging(System.Nullable<bool> value);
    partial void OnPersistentCartEnabledChanged();
    #endregion
		
		public ZNodePortal()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PortalID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int PortalID
		{
			get
			{
				return this._PortalID;
			}
			set
			{
				if ((this._PortalID != value))
				{
					this.OnPortalIDChanging(value);
					this.SendPropertyChanging();
					this._PortalID = value;
					this.SendPropertyChanged("PortalID");
					this.OnPortalIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompanyName", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string CompanyName
		{
			get
			{
				return this._CompanyName;
			}
			set
			{
				if ((this._CompanyName != value))
				{
					this.OnCompanyNameChanging(value);
					this.SendPropertyChanging();
					this._CompanyName = value;
					this.SendPropertyChanged("CompanyName");
					this.OnCompanyNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StoreName", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string StoreName
		{
			get
			{
				return this._StoreName;
			}
			set
			{
				if ((this._StoreName != value))
				{
					this.OnStoreNameChanging(value);
					this.SendPropertyChanging();
					this._StoreName = value;
					this.SendPropertyChanged("StoreName");
					this.OnStoreNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LogoPath", DbType="NVarChar(MAX)")]
		public string LogoPath
		{
			get
			{
				return this._LogoPath;
			}
			set
			{
				if ((this._LogoPath != value))
				{
					this.OnLogoPathChanging(value);
					this.SendPropertyChanging();
					this._LogoPath = value;
					this.SendPropertyChanged("LogoPath");
					this.OnLogoPathChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UseSSL", DbType="Bit NOT NULL")]
		public bool UseSSL
		{
			get
			{
				return this._UseSSL;
			}
			set
			{
				if ((this._UseSSL != value))
				{
					this.OnUseSSLChanging(value);
					this.SendPropertyChanging();
					this._UseSSL = value;
					this.SendPropertyChanged("UseSSL");
					this.OnUseSSLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdminEmail", DbType="NVarChar(MAX)")]
		public string AdminEmail
		{
			get
			{
				return this._AdminEmail;
			}
			set
			{
				if ((this._AdminEmail != value))
				{
					this.OnAdminEmailChanging(value);
					this.SendPropertyChanging();
					this._AdminEmail = value;
					this.SendPropertyChanged("AdminEmail");
					this.OnAdminEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SalesEmail", DbType="NVarChar(MAX)")]
		public string SalesEmail
		{
			get
			{
				return this._SalesEmail;
			}
			set
			{
				if ((this._SalesEmail != value))
				{
					this.OnSalesEmailChanging(value);
					this.SendPropertyChanging();
					this._SalesEmail = value;
					this.SendPropertyChanged("SalesEmail");
					this.OnSalesEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomerServiceEmail", DbType="NVarChar(MAX)")]
		public string CustomerServiceEmail
		{
			get
			{
				return this._CustomerServiceEmail;
			}
			set
			{
				if ((this._CustomerServiceEmail != value))
				{
					this.OnCustomerServiceEmailChanging(value);
					this.SendPropertyChanging();
					this._CustomerServiceEmail = value;
					this.SendPropertyChanged("CustomerServiceEmail");
					this.OnCustomerServiceEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SalesPhoneNumber", DbType="NVarChar(MAX)")]
		public string SalesPhoneNumber
		{
			get
			{
				return this._SalesPhoneNumber;
			}
			set
			{
				if ((this._SalesPhoneNumber != value))
				{
					this.OnSalesPhoneNumberChanging(value);
					this.SendPropertyChanging();
					this._SalesPhoneNumber = value;
					this.SendPropertyChanged("SalesPhoneNumber");
					this.OnSalesPhoneNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomerServicePhoneNumber", DbType="NVarChar(MAX)")]
		public string CustomerServicePhoneNumber
		{
			get
			{
				return this._CustomerServicePhoneNumber;
			}
			set
			{
				if ((this._CustomerServicePhoneNumber != value))
				{
					this.OnCustomerServicePhoneNumberChanging(value);
					this.SendPropertyChanging();
					this._CustomerServicePhoneNumber = value;
					this.SendPropertyChanged("CustomerServicePhoneNumber");
					this.OnCustomerServicePhoneNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ImageNotAvailablePath", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string ImageNotAvailablePath
		{
			get
			{
				return this._ImageNotAvailablePath;
			}
			set
			{
				if ((this._ImageNotAvailablePath != value))
				{
					this.OnImageNotAvailablePathChanging(value);
					this.SendPropertyChanging();
					this._ImageNotAvailablePath = value;
					this.SendPropertyChanged("ImageNotAvailablePath");
					this.OnImageNotAvailablePathChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaxCatalogDisplayColumns", DbType="TinyInt NOT NULL")]
		public byte MaxCatalogDisplayColumns
		{
			get
			{
				return this._MaxCatalogDisplayColumns;
			}
			set
			{
				if ((this._MaxCatalogDisplayColumns != value))
				{
					this.OnMaxCatalogDisplayColumnsChanging(value);
					this.SendPropertyChanging();
					this._MaxCatalogDisplayColumns = value;
					this.SendPropertyChanged("MaxCatalogDisplayColumns");
					this.OnMaxCatalogDisplayColumnsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaxCatalogDisplayItems", DbType="Int NOT NULL")]
		public int MaxCatalogDisplayItems
		{
			get
			{
				return this._MaxCatalogDisplayItems;
			}
			set
			{
				if ((this._MaxCatalogDisplayItems != value))
				{
					this.OnMaxCatalogDisplayItemsChanging(value);
					this.SendPropertyChanging();
					this._MaxCatalogDisplayItems = value;
					this.SendPropertyChanged("MaxCatalogDisplayItems");
					this.OnMaxCatalogDisplayItemsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaxCatalogCategoryDisplayThumbnails", DbType="Int NOT NULL")]
		public int MaxCatalogCategoryDisplayThumbnails
		{
			get
			{
				return this._MaxCatalogCategoryDisplayThumbnails;
			}
			set
			{
				if ((this._MaxCatalogCategoryDisplayThumbnails != value))
				{
					this.OnMaxCatalogCategoryDisplayThumbnailsChanging(value);
					this.SendPropertyChanging();
					this._MaxCatalogCategoryDisplayThumbnails = value;
					this.SendPropertyChanged("MaxCatalogCategoryDisplayThumbnails");
					this.OnMaxCatalogCategoryDisplayThumbnailsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaxCatalogItemSmallThumbnailWidth", DbType="Int NOT NULL")]
		public int MaxCatalogItemSmallThumbnailWidth
		{
			get
			{
				return this._MaxCatalogItemSmallThumbnailWidth;
			}
			set
			{
				if ((this._MaxCatalogItemSmallThumbnailWidth != value))
				{
					this.OnMaxCatalogItemSmallThumbnailWidthChanging(value);
					this.SendPropertyChanging();
					this._MaxCatalogItemSmallThumbnailWidth = value;
					this.SendPropertyChanged("MaxCatalogItemSmallThumbnailWidth");
					this.OnMaxCatalogItemSmallThumbnailWidthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaxCatalogItemSmallWidth", DbType="Int NOT NULL")]
		public int MaxCatalogItemSmallWidth
		{
			get
			{
				return this._MaxCatalogItemSmallWidth;
			}
			set
			{
				if ((this._MaxCatalogItemSmallWidth != value))
				{
					this.OnMaxCatalogItemSmallWidthChanging(value);
					this.SendPropertyChanging();
					this._MaxCatalogItemSmallWidth = value;
					this.SendPropertyChanged("MaxCatalogItemSmallWidth");
					this.OnMaxCatalogItemSmallWidthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaxCatalogItemMediumWidth", DbType="Int NOT NULL")]
		public int MaxCatalogItemMediumWidth
		{
			get
			{
				return this._MaxCatalogItemMediumWidth;
			}
			set
			{
				if ((this._MaxCatalogItemMediumWidth != value))
				{
					this.OnMaxCatalogItemMediumWidthChanging(value);
					this.SendPropertyChanging();
					this._MaxCatalogItemMediumWidth = value;
					this.SendPropertyChanged("MaxCatalogItemMediumWidth");
					this.OnMaxCatalogItemMediumWidthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaxCatalogItemThumbnailWidth", DbType="Int NOT NULL")]
		public int MaxCatalogItemThumbnailWidth
		{
			get
			{
				return this._MaxCatalogItemThumbnailWidth;
			}
			set
			{
				if ((this._MaxCatalogItemThumbnailWidth != value))
				{
					this.OnMaxCatalogItemThumbnailWidthChanging(value);
					this.SendPropertyChanging();
					this._MaxCatalogItemThumbnailWidth = value;
					this.SendPropertyChanged("MaxCatalogItemThumbnailWidth");
					this.OnMaxCatalogItemThumbnailWidthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaxCatalogItemLargeWidth", DbType="Int NOT NULL")]
		public int MaxCatalogItemLargeWidth
		{
			get
			{
				return this._MaxCatalogItemLargeWidth;
			}
			set
			{
				if ((this._MaxCatalogItemLargeWidth != value))
				{
					this.OnMaxCatalogItemLargeWidthChanging(value);
					this.SendPropertyChanging();
					this._MaxCatalogItemLargeWidth = value;
					this.SendPropertyChanged("MaxCatalogItemLargeWidth");
					this.OnMaxCatalogItemLargeWidthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaxCatalogItemCrossSellWidth", DbType="Int NOT NULL")]
		public int MaxCatalogItemCrossSellWidth
		{
			get
			{
				return this._MaxCatalogItemCrossSellWidth;
			}
			set
			{
				if ((this._MaxCatalogItemCrossSellWidth != value))
				{
					this.OnMaxCatalogItemCrossSellWidthChanging(value);
					this.SendPropertyChanging();
					this._MaxCatalogItemCrossSellWidth = value;
					this.SendPropertyChanged("MaxCatalogItemCrossSellWidth");
					this.OnMaxCatalogItemCrossSellWidthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShowSwatchInCategory", DbType="Bit NOT NULL")]
		public bool ShowSwatchInCategory
		{
			get
			{
				return this._ShowSwatchInCategory;
			}
			set
			{
				if ((this._ShowSwatchInCategory != value))
				{
					this.OnShowSwatchInCategoryChanging(value);
					this.SendPropertyChanging();
					this._ShowSwatchInCategory = value;
					this.SendPropertyChanged("ShowSwatchInCategory");
					this.OnShowSwatchInCategoryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShowAlternateImageInCategory", DbType="Bit NOT NULL")]
		public bool ShowAlternateImageInCategory
		{
			get
			{
				return this._ShowAlternateImageInCategory;
			}
			set
			{
				if ((this._ShowAlternateImageInCategory != value))
				{
					this.OnShowAlternateImageInCategoryChanging(value);
					this.SendPropertyChanging();
					this._ShowAlternateImageInCategory = value;
					this.SendPropertyChanged("ShowAlternateImageInCategory");
					this.OnShowAlternateImageInCategoryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ActiveInd", DbType="Bit NOT NULL")]
		public bool ActiveInd
		{
			get
			{
				return this._ActiveInd;
			}
			set
			{
				if ((this._ActiveInd != value))
				{
					this.OnActiveIndChanging(value);
					this.SendPropertyChanging();
					this._ActiveInd = value;
					this.SendPropertyChanged("ActiveInd");
					this.OnActiveIndChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SMTPServer", DbType="NVarChar(MAX)")]
		public string SMTPServer
		{
			get
			{
				return this._SMTPServer;
			}
			set
			{
				if ((this._SMTPServer != value))
				{
					this.OnSMTPServerChanging(value);
					this.SendPropertyChanging();
					this._SMTPServer = value;
					this.SendPropertyChanged("SMTPServer");
					this.OnSMTPServerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SMTPUserName", DbType="NVarChar(MAX)")]
		public string SMTPUserName
		{
			get
			{
				return this._SMTPUserName;
			}
			set
			{
				if ((this._SMTPUserName != value))
				{
					this.OnSMTPUserNameChanging(value);
					this.SendPropertyChanging();
					this._SMTPUserName = value;
					this.SendPropertyChanged("SMTPUserName");
					this.OnSMTPUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SMTPPassword", DbType="NVarChar(MAX)")]
		public string SMTPPassword
		{
			get
			{
				return this._SMTPPassword;
			}
			set
			{
				if ((this._SMTPPassword != value))
				{
					this.OnSMTPPasswordChanging(value);
					this.SendPropertyChanging();
					this._SMTPPassword = value;
					this.SendPropertyChanged("SMTPPassword");
					this.OnSMTPPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SMTPPort", DbType="Int")]
		public System.Nullable<int> SMTPPort
		{
			get
			{
				return this._SMTPPort;
			}
			set
			{
				if ((this._SMTPPort != value))
				{
					this.OnSMTPPortChanging(value);
					this.SendPropertyChanging();
					this._SMTPPort = value;
					this.SendPropertyChanged("SMTPPort");
					this.OnSMTPPortChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SiteWideBottomJavascript", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string SiteWideBottomJavascript
		{
			get
			{
				return this._SiteWideBottomJavascript;
			}
			set
			{
				if ((this._SiteWideBottomJavascript != value))
				{
					this.OnSiteWideBottomJavascriptChanging(value);
					this.SendPropertyChanging();
					this._SiteWideBottomJavascript = value;
					this.SendPropertyChanged("SiteWideBottomJavascript");
					this.OnSiteWideBottomJavascriptChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SiteWideTopJavascript", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string SiteWideTopJavascript
		{
			get
			{
				return this._SiteWideTopJavascript;
			}
			set
			{
				if ((this._SiteWideTopJavascript != value))
				{
					this.OnSiteWideTopJavascriptChanging(value);
					this.SendPropertyChanging();
					this._SiteWideTopJavascript = value;
					this.SendPropertyChanged("SiteWideTopJavascript");
					this.OnSiteWideTopJavascriptChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrderReceiptAffiliateJavascript", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string OrderReceiptAffiliateJavascript
		{
			get
			{
				return this._OrderReceiptAffiliateJavascript;
			}
			set
			{
				if ((this._OrderReceiptAffiliateJavascript != value))
				{
					this.OnOrderReceiptAffiliateJavascriptChanging(value);
					this.SendPropertyChanging();
					this._OrderReceiptAffiliateJavascript = value;
					this.SendPropertyChanged("OrderReceiptAffiliateJavascript");
					this.OnOrderReceiptAffiliateJavascriptChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SiteWideAnalyticsJavascript", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string SiteWideAnalyticsJavascript
		{
			get
			{
				return this._SiteWideAnalyticsJavascript;
			}
			set
			{
				if ((this._SiteWideAnalyticsJavascript != value))
				{
					this.OnSiteWideAnalyticsJavascriptChanging(value);
					this.SendPropertyChanging();
					this._SiteWideAnalyticsJavascript = value;
					this.SendPropertyChanged("SiteWideAnalyticsJavascript");
					this.OnSiteWideAnalyticsJavascriptChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GoogleAnalyticsCode", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string GoogleAnalyticsCode
		{
			get
			{
				return this._GoogleAnalyticsCode;
			}
			set
			{
				if ((this._GoogleAnalyticsCode != value))
				{
					this.OnGoogleAnalyticsCodeChanging(value);
					this.SendPropertyChanging();
					this._GoogleAnalyticsCode = value;
					this.SendPropertyChanged("GoogleAnalyticsCode");
					this.OnGoogleAnalyticsCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UPSUserName", DbType="NVarChar(MAX)")]
		public string UPSUserName
		{
			get
			{
				return this._UPSUserName;
			}
			set
			{
				if ((this._UPSUserName != value))
				{
					this.OnUPSUserNameChanging(value);
					this.SendPropertyChanging();
					this._UPSUserName = value;
					this.SendPropertyChanged("UPSUserName");
					this.OnUPSUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UPSPassword", DbType="NVarChar(MAX)")]
		public string UPSPassword
		{
			get
			{
				return this._UPSPassword;
			}
			set
			{
				if ((this._UPSPassword != value))
				{
					this.OnUPSPasswordChanging(value);
					this.SendPropertyChanging();
					this._UPSPassword = value;
					this.SendPropertyChanged("UPSPassword");
					this.OnUPSPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UPSKey", DbType="NVarChar(MAX)")]
		public string UPSKey
		{
			get
			{
				return this._UPSKey;
			}
			set
			{
				if ((this._UPSKey != value))
				{
					this.OnUPSKeyChanging(value);
					this.SendPropertyChanging();
					this._UPSKey = value;
					this.SendPropertyChanged("UPSKey");
					this.OnUPSKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShippingOriginZipCode", DbType="NVarChar(50)")]
		public string ShippingOriginZipCode
		{
			get
			{
				return this._ShippingOriginZipCode;
			}
			set
			{
				if ((this._ShippingOriginZipCode != value))
				{
					this.OnShippingOriginZipCodeChanging(value);
					this.SendPropertyChanging();
					this._ShippingOriginZipCode = value;
					this.SendPropertyChanged("ShippingOriginZipCode");
					this.OnShippingOriginZipCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MasterPage", DbType="NVarChar(MAX)")]
		public string MasterPage
		{
			get
			{
				return this._MasterPage;
			}
			set
			{
				if ((this._MasterPage != value))
				{
					this.OnMasterPageChanging(value);
					this.SendPropertyChanging();
					this._MasterPage = value;
					this.SendPropertyChanged("MasterPage");
					this.OnMasterPageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShopByPriceMin", DbType="Int NOT NULL")]
		public int ShopByPriceMin
		{
			get
			{
				return this._ShopByPriceMin;
			}
			set
			{
				if ((this._ShopByPriceMin != value))
				{
					this.OnShopByPriceMinChanging(value);
					this.SendPropertyChanging();
					this._ShopByPriceMin = value;
					this.SendPropertyChanged("ShopByPriceMin");
					this.OnShopByPriceMinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShopByPriceMax", DbType="Int NOT NULL")]
		public int ShopByPriceMax
		{
			get
			{
				return this._ShopByPriceMax;
			}
			set
			{
				if ((this._ShopByPriceMax != value))
				{
					this.OnShopByPriceMaxChanging(value);
					this.SendPropertyChanging();
					this._ShopByPriceMax = value;
					this.SendPropertyChanged("ShopByPriceMax");
					this.OnShopByPriceMaxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShopByPriceIncrement", DbType="Int NOT NULL")]
		public int ShopByPriceIncrement
		{
			get
			{
				return this._ShopByPriceIncrement;
			}
			set
			{
				if ((this._ShopByPriceIncrement != value))
				{
					this.OnShopByPriceIncrementChanging(value);
					this.SendPropertyChanging();
					this._ShopByPriceIncrement = value;
					this.SendPropertyChanged("ShopByPriceIncrement");
					this.OnShopByPriceIncrementChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FedExAccountNumber", DbType="NVarChar(MAX)")]
		public string FedExAccountNumber
		{
			get
			{
				return this._FedExAccountNumber;
			}
			set
			{
				if ((this._FedExAccountNumber != value))
				{
					this.OnFedExAccountNumberChanging(value);
					this.SendPropertyChanging();
					this._FedExAccountNumber = value;
					this.SendPropertyChanged("FedExAccountNumber");
					this.OnFedExAccountNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FedExMeterNumber", DbType="NVarChar(MAX)")]
		public string FedExMeterNumber
		{
			get
			{
				return this._FedExMeterNumber;
			}
			set
			{
				if ((this._FedExMeterNumber != value))
				{
					this.OnFedExMeterNumberChanging(value);
					this.SendPropertyChanging();
					this._FedExMeterNumber = value;
					this.SendPropertyChanged("FedExMeterNumber");
					this.OnFedExMeterNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FedExProductionKey", DbType="NVarChar(MAX)")]
		public string FedExProductionKey
		{
			get
			{
				return this._FedExProductionKey;
			}
			set
			{
				if ((this._FedExProductionKey != value))
				{
					this.OnFedExProductionKeyChanging(value);
					this.SendPropertyChanging();
					this._FedExProductionKey = value;
					this.SendPropertyChanged("FedExProductionKey");
					this.OnFedExProductionKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FedExSecurityCode", DbType="NVarChar(MAX)")]
		public string FedExSecurityCode
		{
			get
			{
				return this._FedExSecurityCode;
			}
			set
			{
				if ((this._FedExSecurityCode != value))
				{
					this.OnFedExSecurityCodeChanging(value);
					this.SendPropertyChanging();
					this._FedExSecurityCode = value;
					this.SendPropertyChanged("FedExSecurityCode");
					this.OnFedExSecurityCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FedExCSPKey", DbType="NVarChar(MAX)")]
		public string FedExCSPKey
		{
			get
			{
				return this._FedExCSPKey;
			}
			set
			{
				if ((this._FedExCSPKey != value))
				{
					this.OnFedExCSPKeyChanging(value);
					this.SendPropertyChanging();
					this._FedExCSPKey = value;
					this.SendPropertyChanged("FedExCSPKey");
					this.OnFedExCSPKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FedExCSPPassword", DbType="NVarChar(MAX)")]
		public string FedExCSPPassword
		{
			get
			{
				return this._FedExCSPPassword;
			}
			set
			{
				if ((this._FedExCSPPassword != value))
				{
					this.OnFedExCSPPasswordChanging(value);
					this.SendPropertyChanging();
					this._FedExCSPPassword = value;
					this.SendPropertyChanged("FedExCSPPassword");
					this.OnFedExCSPPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FedExClientProductId", DbType="NVarChar(MAX)")]
		public string FedExClientProductId
		{
			get
			{
				return this._FedExClientProductId;
			}
			set
			{
				if ((this._FedExClientProductId != value))
				{
					this.OnFedExClientProductIdChanging(value);
					this.SendPropertyChanging();
					this._FedExClientProductId = value;
					this.SendPropertyChanged("FedExClientProductId");
					this.OnFedExClientProductIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FedExClientProductVersion", DbType="NVarChar(MAX)")]
		public string FedExClientProductVersion
		{
			get
			{
				return this._FedExClientProductVersion;
			}
			set
			{
				if ((this._FedExClientProductVersion != value))
				{
					this.OnFedExClientProductVersionChanging(value);
					this.SendPropertyChanging();
					this._FedExClientProductVersion = value;
					this.SendPropertyChanged("FedExClientProductVersion");
					this.OnFedExClientProductVersionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FedExDropoffType", DbType="NVarChar(MAX)")]
		public string FedExDropoffType
		{
			get
			{
				return this._FedExDropoffType;
			}
			set
			{
				if ((this._FedExDropoffType != value))
				{
					this.OnFedExDropoffTypeChanging(value);
					this.SendPropertyChanging();
					this._FedExDropoffType = value;
					this.SendPropertyChanged("FedExDropoffType");
					this.OnFedExDropoffTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FedExPackagingType", DbType="NVarChar(MAX)")]
		public string FedExPackagingType
		{
			get
			{
				return this._FedExPackagingType;
			}
			set
			{
				if ((this._FedExPackagingType != value))
				{
					this.OnFedExPackagingTypeChanging(value);
					this.SendPropertyChanging();
					this._FedExPackagingType = value;
					this.SendPropertyChanged("FedExPackagingType");
					this.OnFedExPackagingTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FedExUseDiscountRate", DbType="Bit")]
		public System.Nullable<bool> FedExUseDiscountRate
		{
			get
			{
				return this._FedExUseDiscountRate;
			}
			set
			{
				if ((this._FedExUseDiscountRate != value))
				{
					this.OnFedExUseDiscountRateChanging(value);
					this.SendPropertyChanging();
					this._FedExUseDiscountRate = value;
					this.SendPropertyChanged("FedExUseDiscountRate");
					this.OnFedExUseDiscountRateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FedExAddInsurance", DbType="Bit")]
		public System.Nullable<bool> FedExAddInsurance
		{
			get
			{
				return this._FedExAddInsurance;
			}
			set
			{
				if ((this._FedExAddInsurance != value))
				{
					this.OnFedExAddInsuranceChanging(value);
					this.SendPropertyChanging();
					this._FedExAddInsurance = value;
					this.SendPropertyChanged("FedExAddInsurance");
					this.OnFedExAddInsuranceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShippingOriginAddress1", DbType="NVarChar(MAX)")]
		public string ShippingOriginAddress1
		{
			get
			{
				return this._ShippingOriginAddress1;
			}
			set
			{
				if ((this._ShippingOriginAddress1 != value))
				{
					this.OnShippingOriginAddress1Changing(value);
					this.SendPropertyChanging();
					this._ShippingOriginAddress1 = value;
					this.SendPropertyChanged("ShippingOriginAddress1");
					this.OnShippingOriginAddress1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShippingOriginAddress2", DbType="NVarChar(MAX)")]
		public string ShippingOriginAddress2
		{
			get
			{
				return this._ShippingOriginAddress2;
			}
			set
			{
				if ((this._ShippingOriginAddress2 != value))
				{
					this.OnShippingOriginAddress2Changing(value);
					this.SendPropertyChanging();
					this._ShippingOriginAddress2 = value;
					this.SendPropertyChanged("ShippingOriginAddress2");
					this.OnShippingOriginAddress2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShippingOriginCity", DbType="NVarChar(MAX)")]
		public string ShippingOriginCity
		{
			get
			{
				return this._ShippingOriginCity;
			}
			set
			{
				if ((this._ShippingOriginCity != value))
				{
					this.OnShippingOriginCityChanging(value);
					this.SendPropertyChanging();
					this._ShippingOriginCity = value;
					this.SendPropertyChanged("ShippingOriginCity");
					this.OnShippingOriginCityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShippingOriginStateCode", DbType="NVarChar(MAX)")]
		public string ShippingOriginStateCode
		{
			get
			{
				return this._ShippingOriginStateCode;
			}
			set
			{
				if ((this._ShippingOriginStateCode != value))
				{
					this.OnShippingOriginStateCodeChanging(value);
					this.SendPropertyChanging();
					this._ShippingOriginStateCode = value;
					this.SendPropertyChanged("ShippingOriginStateCode");
					this.OnShippingOriginStateCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShippingOriginCountryCode", DbType="NVarChar(MAX)")]
		public string ShippingOriginCountryCode
		{
			get
			{
				return this._ShippingOriginCountryCode;
			}
			set
			{
				if ((this._ShippingOriginCountryCode != value))
				{
					this.OnShippingOriginCountryCodeChanging(value);
					this.SendPropertyChanging();
					this._ShippingOriginCountryCode = value;
					this.SendPropertyChanged("ShippingOriginCountryCode");
					this.OnShippingOriginCountryCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShippingOriginPhone", DbType="NVarChar(MAX)")]
		public string ShippingOriginPhone
		{
			get
			{
				return this._ShippingOriginPhone;
			}
			set
			{
				if ((this._ShippingOriginPhone != value))
				{
					this.OnShippingOriginPhoneChanging(value);
					this.SendPropertyChanging();
					this._ShippingOriginPhone = value;
					this.SendPropertyChanged("ShippingOriginPhone");
					this.OnShippingOriginPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CurrencyTypeID", DbType="Int")]
		public System.Nullable<int> CurrencyTypeID
		{
			get
			{
				return this._CurrencyTypeID;
			}
			set
			{
				if ((this._CurrencyTypeID != value))
				{
					this.OnCurrencyTypeIDChanging(value);
					this.SendPropertyChanging();
					this._CurrencyTypeID = value;
					this.SendPropertyChanged("CurrencyTypeID");
					this.OnCurrencyTypeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WeightUnit", DbType="NVarChar(MAX)")]
		public string WeightUnit
		{
			get
			{
				return this._WeightUnit;
			}
			set
			{
				if ((this._WeightUnit != value))
				{
					this.OnWeightUnitChanging(value);
					this.SendPropertyChanging();
					this._WeightUnit = value;
					this.SendPropertyChanged("WeightUnit");
					this.OnWeightUnitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DimensionUnit", DbType="NVarChar(MAX)")]
		public string DimensionUnit
		{
			get
			{
				return this._DimensionUnit;
			}
			set
			{
				if ((this._DimensionUnit != value))
				{
					this.OnDimensionUnitChanging(value);
					this.SendPropertyChanging();
					this._DimensionUnit = value;
					this.SendPropertyChanged("DimensionUnit");
					this.OnDimensionUnitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailListLogin", DbType="NVarChar(100)")]
		public string EmailListLogin
		{
			get
			{
				return this._EmailListLogin;
			}
			set
			{
				if ((this._EmailListLogin != value))
				{
					this.OnEmailListLoginChanging(value);
					this.SendPropertyChanging();
					this._EmailListLogin = value;
					this.SendPropertyChanged("EmailListLogin");
					this.OnEmailListLoginChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailListPassword", DbType="NVarChar(100)")]
		public string EmailListPassword
		{
			get
			{
				return this._EmailListPassword;
			}
			set
			{
				if ((this._EmailListPassword != value))
				{
					this.OnEmailListPasswordChanging(value);
					this.SendPropertyChanging();
					this._EmailListPassword = value;
					this.SendPropertyChanged("EmailListPassword");
					this.OnEmailListPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailListDefaultList", DbType="NVarChar(MAX)")]
		public string EmailListDefaultList
		{
			get
			{
				return this._EmailListDefaultList;
			}
			set
			{
				if ((this._EmailListDefaultList != value))
				{
					this.OnEmailListDefaultListChanging(value);
					this.SendPropertyChanging();
					this._EmailListDefaultList = value;
					this.SendPropertyChanged("EmailListDefaultList");
					this.OnEmailListDefaultListChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShippingTaxable", DbType="Bit NOT NULL")]
		public bool ShippingTaxable
		{
			get
			{
				return this._ShippingTaxable;
			}
			set
			{
				if ((this._ShippingTaxable != value))
				{
					this.OnShippingTaxableChanging(value);
					this.SendPropertyChanging();
					this._ShippingTaxable = value;
					this.SendPropertyChanged("ShippingTaxable");
					this.OnShippingTaxableChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DefaultOrderStateID", DbType="Int")]
		public System.Nullable<int> DefaultOrderStateID
		{
			get
			{
				return this._DefaultOrderStateID;
			}
			set
			{
				if ((this._DefaultOrderStateID != value))
				{
					this.OnDefaultOrderStateIDChanging(value);
					this.SendPropertyChanging();
					this._DefaultOrderStateID = value;
					this.SendPropertyChanged("DefaultOrderStateID");
					this.OnDefaultOrderStateIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DefaultReviewStatus", DbType="NVarChar(1)")]
		public string DefaultReviewStatus
		{
			get
			{
				return this._DefaultReviewStatus;
			}
			set
			{
				if ((this._DefaultReviewStatus != value))
				{
					this.OnDefaultReviewStatusChanging(value);
					this.SendPropertyChanging();
					this._DefaultReviewStatus = value;
					this.SendPropertyChanged("DefaultReviewStatus");
					this.OnDefaultReviewStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DefaultAnonymousProfileID", DbType="Int")]
		public System.Nullable<int> DefaultAnonymousProfileID
		{
			get
			{
				return this._DefaultAnonymousProfileID;
			}
			set
			{
				if ((this._DefaultAnonymousProfileID != value))
				{
					this.OnDefaultAnonymousProfileIDChanging(value);
					this.SendPropertyChanging();
					this._DefaultAnonymousProfileID = value;
					this.SendPropertyChanged("DefaultAnonymousProfileID");
					this.OnDefaultAnonymousProfileIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DefaultRegisteredProfileID", DbType="Int")]
		public System.Nullable<int> DefaultRegisteredProfileID
		{
			get
			{
				return this._DefaultRegisteredProfileID;
			}
			set
			{
				if ((this._DefaultRegisteredProfileID != value))
				{
					this.OnDefaultRegisteredProfileIDChanging(value);
					this.SendPropertyChanging();
					this._DefaultRegisteredProfileID = value;
					this.SendPropertyChanged("DefaultRegisteredProfileID");
					this.OnDefaultRegisteredProfileIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InclusiveTax", DbType="Bit NOT NULL")]
		public bool InclusiveTax
		{
			get
			{
				return this._InclusiveTax;
			}
			set
			{
				if ((this._InclusiveTax != value))
				{
					this.OnInclusiveTaxChanging(value);
					this.SendPropertyChanging();
					this._InclusiveTax = value;
					this.SendPropertyChanged("InclusiveTax");
					this.OnInclusiveTaxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SeoDefaultProductTitle", DbType="NVarChar(MAX)")]
		public string SeoDefaultProductTitle
		{
			get
			{
				return this._SeoDefaultProductTitle;
			}
			set
			{
				if ((this._SeoDefaultProductTitle != value))
				{
					this.OnSeoDefaultProductTitleChanging(value);
					this.SendPropertyChanging();
					this._SeoDefaultProductTitle = value;
					this.SendPropertyChanged("SeoDefaultProductTitle");
					this.OnSeoDefaultProductTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SeoDefaultProductDescription", DbType="NVarChar(MAX)")]
		public string SeoDefaultProductDescription
		{
			get
			{
				return this._SeoDefaultProductDescription;
			}
			set
			{
				if ((this._SeoDefaultProductDescription != value))
				{
					this.OnSeoDefaultProductDescriptionChanging(value);
					this.SendPropertyChanging();
					this._SeoDefaultProductDescription = value;
					this.SendPropertyChanged("SeoDefaultProductDescription");
					this.OnSeoDefaultProductDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SeoDefaultProductKeyword", DbType="NVarChar(MAX)")]
		public string SeoDefaultProductKeyword
		{
			get
			{
				return this._SeoDefaultProductKeyword;
			}
			set
			{
				if ((this._SeoDefaultProductKeyword != value))
				{
					this.OnSeoDefaultProductKeywordChanging(value);
					this.SendPropertyChanging();
					this._SeoDefaultProductKeyword = value;
					this.SendPropertyChanged("SeoDefaultProductKeyword");
					this.OnSeoDefaultProductKeywordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SeoDefaultCategoryTitle", DbType="NVarChar(MAX)")]
		public string SeoDefaultCategoryTitle
		{
			get
			{
				return this._SeoDefaultCategoryTitle;
			}
			set
			{
				if ((this._SeoDefaultCategoryTitle != value))
				{
					this.OnSeoDefaultCategoryTitleChanging(value);
					this.SendPropertyChanging();
					this._SeoDefaultCategoryTitle = value;
					this.SendPropertyChanged("SeoDefaultCategoryTitle");
					this.OnSeoDefaultCategoryTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SeoDefaultCategoryDescription", DbType="NVarChar(MAX)")]
		public string SeoDefaultCategoryDescription
		{
			get
			{
				return this._SeoDefaultCategoryDescription;
			}
			set
			{
				if ((this._SeoDefaultCategoryDescription != value))
				{
					this.OnSeoDefaultCategoryDescriptionChanging(value);
					this.SendPropertyChanging();
					this._SeoDefaultCategoryDescription = value;
					this.SendPropertyChanged("SeoDefaultCategoryDescription");
					this.OnSeoDefaultCategoryDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SeoDefaultCategoryKeyword", DbType="NVarChar(MAX)")]
		public string SeoDefaultCategoryKeyword
		{
			get
			{
				return this._SeoDefaultCategoryKeyword;
			}
			set
			{
				if ((this._SeoDefaultCategoryKeyword != value))
				{
					this.OnSeoDefaultCategoryKeywordChanging(value);
					this.SendPropertyChanging();
					this._SeoDefaultCategoryKeyword = value;
					this.SendPropertyChanged("SeoDefaultCategoryKeyword");
					this.OnSeoDefaultCategoryKeywordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SeoDefaultContentTitle", DbType="NVarChar(MAX)")]
		public string SeoDefaultContentTitle
		{
			get
			{
				return this._SeoDefaultContentTitle;
			}
			set
			{
				if ((this._SeoDefaultContentTitle != value))
				{
					this.OnSeoDefaultContentTitleChanging(value);
					this.SendPropertyChanging();
					this._SeoDefaultContentTitle = value;
					this.SendPropertyChanged("SeoDefaultContentTitle");
					this.OnSeoDefaultContentTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SeoDefaultContentDescription", DbType="NVarChar(MAX)")]
		public string SeoDefaultContentDescription
		{
			get
			{
				return this._SeoDefaultContentDescription;
			}
			set
			{
				if ((this._SeoDefaultContentDescription != value))
				{
					this.OnSeoDefaultContentDescriptionChanging(value);
					this.SendPropertyChanging();
					this._SeoDefaultContentDescription = value;
					this.SendPropertyChanged("SeoDefaultContentDescription");
					this.OnSeoDefaultContentDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SeoDefaultContentKeyword", DbType="NVarChar(MAX)")]
		public string SeoDefaultContentKeyword
		{
			get
			{
				return this._SeoDefaultContentKeyword;
			}
			set
			{
				if ((this._SeoDefaultContentKeyword != value))
				{
					this.OnSeoDefaultContentKeywordChanging(value);
					this.SendPropertyChanging();
					this._SeoDefaultContentKeyword = value;
					this.SendPropertyChanged("SeoDefaultContentKeyword");
					this.OnSeoDefaultContentKeywordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimeZoneOffset", DbType="NVarChar(50)")]
		public string TimeZoneOffset
		{
			get
			{
				return this._TimeZoneOffset;
			}
			set
			{
				if ((this._TimeZoneOffset != value))
				{
					this.OnTimeZoneOffsetChanging(value);
					this.SendPropertyChanging();
					this._TimeZoneOffset = value;
					this.SendPropertyChanged("TimeZoneOffset");
					this.OnTimeZoneOffsetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LocaleID", DbType="Int NOT NULL")]
		public int LocaleID
		{
			get
			{
				return this._LocaleID;
			}
			set
			{
				if ((this._LocaleID != value))
				{
					this.OnLocaleIDChanging(value);
					this.SendPropertyChanging();
					this._LocaleID = value;
					this.SendPropertyChanged("LocaleID");
					this.OnLocaleIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SplashCategoryID", DbType="Int")]
		public System.Nullable<int> SplashCategoryID
		{
			get
			{
				return this._SplashCategoryID;
			}
			set
			{
				if ((this._SplashCategoryID != value))
				{
					this.OnSplashCategoryIDChanging(value);
					this.SendPropertyChanging();
					this._SplashCategoryID = value;
					this.SendPropertyChanged("SplashCategoryID");
					this.OnSplashCategoryIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SplashImageFile", DbType="NVarChar(MAX)")]
		public string SplashImageFile
		{
			get
			{
				return this._SplashImageFile;
			}
			set
			{
				if ((this._SplashImageFile != value))
				{
					this.OnSplashImageFileChanging(value);
					this.SendPropertyChanging();
					this._SplashImageFile = value;
					this.SendPropertyChanged("SplashImageFile");
					this.OnSplashImageFileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MobileTheme", DbType="NVarChar(MAX)")]
		public string MobileTheme
		{
			get
			{
				return this._MobileTheme;
			}
			set
			{
				if ((this._MobileTheme != value))
				{
					this.OnMobileThemeChanging(value);
					this.SendPropertyChanging();
					this._MobileTheme = value;
					this.SendPropertyChanged("MobileTheme");
					this.OnMobileThemeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PersistentCartEnabled", DbType="Bit")]
		public System.Nullable<bool> PersistentCartEnabled
		{
			get
			{
				return this._PersistentCartEnabled;
			}
			set
			{
				if ((this._PersistentCartEnabled != value))
				{
					this.OnPersistentCartEnabledChanging(value);
					this.SendPropertyChanging();
					this._PersistentCartEnabled = value;
					this.SendPropertyChanged("PersistentCartEnabled");
					this.OnPersistentCartEnabledChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
