#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace store_api_test.DataMapping
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="znode_multifront")]
	public partial class ProductDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertZNodeProduct(ZNodeProduct instance);
    partial void UpdateZNodeProduct(ZNodeProduct instance);
    partial void DeleteZNodeProduct(ZNodeProduct instance);
    #endregion
		
		public ProductDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["znode_multifrontConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ProductDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ProductDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ProductDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ProductDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ZNodeProduct> ZNodeProducts
		{
			get
			{
				return this.GetTable<ZNodeProduct>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ZNodeProduct")]
	public partial class ZNodeProduct : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ProductID;
		
		private string _Name;
		
		private string _ShortDescription;
		
		private string _Description;
		
		private string _FeaturesDesc;
		
		private string _ProductNum;
		
		private int _ProductTypeID;
		
		private System.Nullable<decimal> _RetailPrice;
		
		private System.Nullable<decimal> _SalePrice;
		
		private System.Nullable<decimal> _WholesalePrice;
		
		private string _ImageFile;
		
		private string _ImageAltTag;
		
		private System.Nullable<decimal> _Weight;
		
		private System.Nullable<decimal> _Length;
		
		private System.Nullable<decimal> _Width;
		
		private System.Nullable<decimal> _Height;
		
		private System.Nullable<System.DateTime> _BeginActiveDate;
		
		private System.Nullable<System.DateTime> _EndActiveDate;
		
		private System.Nullable<int> _DisplayOrder;
		
		private bool _ActiveInd;
		
		private bool _CallForPricing;
		
		private bool _HomepageSpecial;
		
		private bool _CategorySpecial;
		
		private byte _InventoryDisplay;
		
		private string _Keywords;
		
		private System.Nullable<int> _ManufacturerID;
		
		private string _AdditionalInfoLink;
		
		private string _AdditionalInfoLinkLabel;
		
		private System.Nullable<int> _ShippingRuleTypeID;
		
		private System.Nullable<decimal> _ShippingRate;
		
		private string _SEOTitle;
		
		private string _SEOKeywords;
		
		private string _SEODescription;
		
		private string _Custom1;
		
		private string _Custom2;
		
		private string _Custom3;
		
		private System.Nullable<bool> _ShipEachItemSeparately;
		
		private System.Nullable<bool> _AllowBackOrder;
		
		private string _BackOrderMsg;
		
		private System.Nullable<bool> _DropShipInd;
		
		private string _DropShipEmailID;
		
		private string _Specifications;
		
		private string _AdditionalInformation;
		
		private string _InStockMsg;
		
		private string _OutOfStockMsg;
		
		private System.Nullable<bool> _TrackInventoryInd;
		
		private string _DownloadLink;
		
		private System.Nullable<bool> _FreeShippingInd;
		
		private System.Nullable<bool> _NewProductInd;
		
		private string _SEOURL;
		
		private System.Nullable<int> _MaxQty;
		
		private bool _ShipSeparately;
		
		private bool _FeaturedInd;
		
		private System.Nullable<System.DateTime> _WebServiceDownloadDte;
		
		private System.Nullable<System.DateTime> _UpdateDte;
		
		private System.Nullable<int> _SupplierID;
		
		private bool _RecurringBillingInd;
		
		private bool _RecurringBillingInstallmentInd;
		
		private string _RecurringBillingPeriod;
		
		private string _RecurringBillingFrequency;
		
		private System.Nullable<int> _RecurringBillingTotalCycles;
		
		private System.Nullable<decimal> _RecurringBillingInitialAmount;
		
		private System.Nullable<int> _TaxClassID;
		
		private System.Nullable<int> _MinQty;
		
		private System.Nullable<int> _ReviewStateID;
		
		private string _AffiliateUrl;
		
		private System.Nullable<bool> _IsShippable;
		
		private System.Nullable<int> _AccountID;
		
		private System.Nullable<int> _PortalID;
		
		private bool _Franchisable;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnProductIDChanging(int value);
    partial void OnProductIDChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnShortDescriptionChanging(string value);
    partial void OnShortDescriptionChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnFeaturesDescChanging(string value);
    partial void OnFeaturesDescChanged();
    partial void OnProductNumChanging(string value);
    partial void OnProductNumChanged();
    partial void OnProductTypeIDChanging(int value);
    partial void OnProductTypeIDChanged();
    partial void OnRetailPriceChanging(System.Nullable<decimal> value);
    partial void OnRetailPriceChanged();
    partial void OnSalePriceChanging(System.Nullable<decimal> value);
    partial void OnSalePriceChanged();
    partial void OnWholesalePriceChanging(System.Nullable<decimal> value);
    partial void OnWholesalePriceChanged();
    partial void OnImageFileChanging(string value);
    partial void OnImageFileChanged();
    partial void OnImageAltTagChanging(string value);
    partial void OnImageAltTagChanged();
    partial void OnWeightChanging(System.Nullable<decimal> value);
    partial void OnWeightChanged();
    partial void OnLengthChanging(System.Nullable<decimal> value);
    partial void OnLengthChanged();
    partial void OnWidthChanging(System.Nullable<decimal> value);
    partial void OnWidthChanged();
    partial void OnHeightChanging(System.Nullable<decimal> value);
    partial void OnHeightChanged();
    partial void OnBeginActiveDateChanging(System.Nullable<System.DateTime> value);
    partial void OnBeginActiveDateChanged();
    partial void OnEndActiveDateChanging(System.Nullable<System.DateTime> value);
    partial void OnEndActiveDateChanged();
    partial void OnDisplayOrderChanging(System.Nullable<int> value);
    partial void OnDisplayOrderChanged();
    partial void OnActiveIndChanging(bool value);
    partial void OnActiveIndChanged();
    partial void OnCallForPricingChanging(bool value);
    partial void OnCallForPricingChanged();
    partial void OnHomepageSpecialChanging(bool value);
    partial void OnHomepageSpecialChanged();
    partial void OnCategorySpecialChanging(bool value);
    partial void OnCategorySpecialChanged();
    partial void OnInventoryDisplayChanging(byte value);
    partial void OnInventoryDisplayChanged();
    partial void OnKeywordsChanging(string value);
    partial void OnKeywordsChanged();
    partial void OnManufacturerIDChanging(System.Nullable<int> value);
    partial void OnManufacturerIDChanged();
    partial void OnAdditionalInfoLinkChanging(string value);
    partial void OnAdditionalInfoLinkChanged();
    partial void OnAdditionalInfoLinkLabelChanging(string value);
    partial void OnAdditionalInfoLinkLabelChanged();
    partial void OnShippingRuleTypeIDChanging(System.Nullable<int> value);
    partial void OnShippingRuleTypeIDChanged();
    partial void OnShippingRateChanging(System.Nullable<decimal> value);
    partial void OnShippingRateChanged();
    partial void OnSEOTitleChanging(string value);
    partial void OnSEOTitleChanged();
    partial void OnSEOKeywordsChanging(string value);
    partial void OnSEOKeywordsChanged();
    partial void OnSEODescriptionChanging(string value);
    partial void OnSEODescriptionChanged();
    partial void OnCustom1Changing(string value);
    partial void OnCustom1Changed();
    partial void OnCustom2Changing(string value);
    partial void OnCustom2Changed();
    partial void OnCustom3Changing(string value);
    partial void OnCustom3Changed();
    partial void OnShipEachItemSeparatelyChanging(System.Nullable<bool> value);
    partial void OnShipEachItemSeparatelyChanged();
    partial void OnAllowBackOrderChanging(System.Nullable<bool> value);
    partial void OnAllowBackOrderChanged();
    partial void OnBackOrderMsgChanging(string value);
    partial void OnBackOrderMsgChanged();
    partial void OnDropShipIndChanging(System.Nullable<bool> value);
    partial void OnDropShipIndChanged();
    partial void OnDropShipEmailIDChanging(string value);
    partial void OnDropShipEmailIDChanged();
    partial void OnSpecificationsChanging(string value);
    partial void OnSpecificationsChanged();
    partial void OnAdditionalInformationChanging(string value);
    partial void OnAdditionalInformationChanged();
    partial void OnInStockMsgChanging(string value);
    partial void OnInStockMsgChanged();
    partial void OnOutOfStockMsgChanging(string value);
    partial void OnOutOfStockMsgChanged();
    partial void OnTrackInventoryIndChanging(System.Nullable<bool> value);
    partial void OnTrackInventoryIndChanged();
    partial void OnDownloadLinkChanging(string value);
    partial void OnDownloadLinkChanged();
    partial void OnFreeShippingIndChanging(System.Nullable<bool> value);
    partial void OnFreeShippingIndChanged();
    partial void OnNewProductIndChanging(System.Nullable<bool> value);
    partial void OnNewProductIndChanged();
    partial void OnSEOURLChanging(string value);
    partial void OnSEOURLChanged();
    partial void OnMaxQtyChanging(System.Nullable<int> value);
    partial void OnMaxQtyChanged();
    partial void OnShipSeparatelyChanging(bool value);
    partial void OnShipSeparatelyChanged();
    partial void OnFeaturedIndChanging(bool value);
    partial void OnFeaturedIndChanged();
    partial void OnWebServiceDownloadDteChanging(System.Nullable<System.DateTime> value);
    partial void OnWebServiceDownloadDteChanged();
    partial void OnUpdateDteChanging(System.Nullable<System.DateTime> value);
    partial void OnUpdateDteChanged();
    partial void OnSupplierIDChanging(System.Nullable<int> value);
    partial void OnSupplierIDChanged();
    partial void OnRecurringBillingIndChanging(bool value);
    partial void OnRecurringBillingIndChanged();
    partial void OnRecurringBillingInstallmentIndChanging(bool value);
    partial void OnRecurringBillingInstallmentIndChanged();
    partial void OnRecurringBillingPeriodChanging(string value);
    partial void OnRecurringBillingPeriodChanged();
    partial void OnRecurringBillingFrequencyChanging(string value);
    partial void OnRecurringBillingFrequencyChanged();
    partial void OnRecurringBillingTotalCyclesChanging(System.Nullable<int> value);
    partial void OnRecurringBillingTotalCyclesChanged();
    partial void OnRecurringBillingInitialAmountChanging(System.Nullable<decimal> value);
    partial void OnRecurringBillingInitialAmountChanged();
    partial void OnTaxClassIDChanging(System.Nullable<int> value);
    partial void OnTaxClassIDChanged();
    partial void OnMinQtyChanging(System.Nullable<int> value);
    partial void OnMinQtyChanged();
    partial void OnReviewStateIDChanging(System.Nullable<int> value);
    partial void OnReviewStateIDChanged();
    partial void OnAffiliateUrlChanging(string value);
    partial void OnAffiliateUrlChanged();
    partial void OnIsShippableChanging(System.Nullable<bool> value);
    partial void OnIsShippableChanged();
    partial void OnAccountIDChanging(System.Nullable<int> value);
    partial void OnAccountIDChanged();
    partial void OnPortalIDChanging(System.Nullable<int> value);
    partial void OnPortalIDChanged();
    partial void OnFranchisableChanging(bool value);
    partial void OnFranchisableChanged();
    #endregion
		
		public ZNodeProduct()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ProductID
		{
			get
			{
				return this._ProductID;
			}
			set
			{
				if ((this._ProductID != value))
				{
					this.OnProductIDChanging(value);
					this.SendPropertyChanging();
					this._ProductID = value;
					this.SendPropertyChanged("ProductID");
					this.OnProductIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShortDescription", DbType="NVarChar(MAX)")]
		public string ShortDescription
		{
			get
			{
				return this._ShortDescription;
			}
			set
			{
				if ((this._ShortDescription != value))
				{
					this.OnShortDescriptionChanging(value);
					this.SendPropertyChanging();
					this._ShortDescription = value;
					this.SendPropertyChanged("ShortDescription");
					this.OnShortDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FeaturesDesc", DbType="NVarChar(MAX)")]
		public string FeaturesDesc
		{
			get
			{
				return this._FeaturesDesc;
			}
			set
			{
				if ((this._FeaturesDesc != value))
				{
					this.OnFeaturesDescChanging(value);
					this.SendPropertyChanging();
					this._FeaturesDesc = value;
					this.SendPropertyChanged("FeaturesDesc");
					this.OnFeaturesDescChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductNum", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string ProductNum
		{
			get
			{
				return this._ProductNum;
			}
			set
			{
				if ((this._ProductNum != value))
				{
					this.OnProductNumChanging(value);
					this.SendPropertyChanging();
					this._ProductNum = value;
					this.SendPropertyChanged("ProductNum");
					this.OnProductNumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductTypeID", DbType="Int NOT NULL")]
		public int ProductTypeID
		{
			get
			{
				return this._ProductTypeID;
			}
			set
			{
				if ((this._ProductTypeID != value))
				{
					this.OnProductTypeIDChanging(value);
					this.SendPropertyChanging();
					this._ProductTypeID = value;
					this.SendPropertyChanged("ProductTypeID");
					this.OnProductTypeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RetailPrice", DbType="Money")]
		public System.Nullable<decimal> RetailPrice
		{
			get
			{
				return this._RetailPrice;
			}
			set
			{
				if ((this._RetailPrice != value))
				{
					this.OnRetailPriceChanging(value);
					this.SendPropertyChanging();
					this._RetailPrice = value;
					this.SendPropertyChanged("RetailPrice");
					this.OnRetailPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SalePrice", DbType="Money")]
		public System.Nullable<decimal> SalePrice
		{
			get
			{
				return this._SalePrice;
			}
			set
			{
				if ((this._SalePrice != value))
				{
					this.OnSalePriceChanging(value);
					this.SendPropertyChanging();
					this._SalePrice = value;
					this.SendPropertyChanged("SalePrice");
					this.OnSalePriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WholesalePrice", DbType="Money")]
		public System.Nullable<decimal> WholesalePrice
		{
			get
			{
				return this._WholesalePrice;
			}
			set
			{
				if ((this._WholesalePrice != value))
				{
					this.OnWholesalePriceChanging(value);
					this.SendPropertyChanging();
					this._WholesalePrice = value;
					this.SendPropertyChanged("WholesalePrice");
					this.OnWholesalePriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ImageFile", DbType="NVarChar(MAX)")]
		public string ImageFile
		{
			get
			{
				return this._ImageFile;
			}
			set
			{
				if ((this._ImageFile != value))
				{
					this.OnImageFileChanging(value);
					this.SendPropertyChanging();
					this._ImageFile = value;
					this.SendPropertyChanged("ImageFile");
					this.OnImageFileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ImageAltTag", DbType="NVarChar(MAX)")]
		public string ImageAltTag
		{
			get
			{
				return this._ImageAltTag;
			}
			set
			{
				if ((this._ImageAltTag != value))
				{
					this.OnImageAltTagChanging(value);
					this.SendPropertyChanging();
					this._ImageAltTag = value;
					this.SendPropertyChanged("ImageAltTag");
					this.OnImageAltTagChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Weight", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> Weight
		{
			get
			{
				return this._Weight;
			}
			set
			{
				if ((this._Weight != value))
				{
					this.OnWeightChanging(value);
					this.SendPropertyChanging();
					this._Weight = value;
					this.SendPropertyChanged("Weight");
					this.OnWeightChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Length", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> Length
		{
			get
			{
				return this._Length;
			}
			set
			{
				if ((this._Length != value))
				{
					this.OnLengthChanging(value);
					this.SendPropertyChanging();
					this._Length = value;
					this.SendPropertyChanged("Length");
					this.OnLengthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Width", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> Width
		{
			get
			{
				return this._Width;
			}
			set
			{
				if ((this._Width != value))
				{
					this.OnWidthChanging(value);
					this.SendPropertyChanging();
					this._Width = value;
					this.SendPropertyChanged("Width");
					this.OnWidthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Height", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> Height
		{
			get
			{
				return this._Height;
			}
			set
			{
				if ((this._Height != value))
				{
					this.OnHeightChanging(value);
					this.SendPropertyChanging();
					this._Height = value;
					this.SendPropertyChanged("Height");
					this.OnHeightChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BeginActiveDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> BeginActiveDate
		{
			get
			{
				return this._BeginActiveDate;
			}
			set
			{
				if ((this._BeginActiveDate != value))
				{
					this.OnBeginActiveDateChanging(value);
					this.SendPropertyChanging();
					this._BeginActiveDate = value;
					this.SendPropertyChanged("BeginActiveDate");
					this.OnBeginActiveDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EndActiveDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> EndActiveDate
		{
			get
			{
				return this._EndActiveDate;
			}
			set
			{
				if ((this._EndActiveDate != value))
				{
					this.OnEndActiveDateChanging(value);
					this.SendPropertyChanging();
					this._EndActiveDate = value;
					this.SendPropertyChanged("EndActiveDate");
					this.OnEndActiveDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DisplayOrder", DbType="Int")]
		public System.Nullable<int> DisplayOrder
		{
			get
			{
				return this._DisplayOrder;
			}
			set
			{
				if ((this._DisplayOrder != value))
				{
					this.OnDisplayOrderChanging(value);
					this.SendPropertyChanging();
					this._DisplayOrder = value;
					this.SendPropertyChanged("DisplayOrder");
					this.OnDisplayOrderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ActiveInd", DbType="Bit NOT NULL")]
		public bool ActiveInd
		{
			get
			{
				return this._ActiveInd;
			}
			set
			{
				if ((this._ActiveInd != value))
				{
					this.OnActiveIndChanging(value);
					this.SendPropertyChanging();
					this._ActiveInd = value;
					this.SendPropertyChanged("ActiveInd");
					this.OnActiveIndChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CallForPricing", DbType="Bit NOT NULL")]
		public bool CallForPricing
		{
			get
			{
				return this._CallForPricing;
			}
			set
			{
				if ((this._CallForPricing != value))
				{
					this.OnCallForPricingChanging(value);
					this.SendPropertyChanging();
					this._CallForPricing = value;
					this.SendPropertyChanged("CallForPricing");
					this.OnCallForPricingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HomepageSpecial", DbType="Bit NOT NULL")]
		public bool HomepageSpecial
		{
			get
			{
				return this._HomepageSpecial;
			}
			set
			{
				if ((this._HomepageSpecial != value))
				{
					this.OnHomepageSpecialChanging(value);
					this.SendPropertyChanging();
					this._HomepageSpecial = value;
					this.SendPropertyChanged("HomepageSpecial");
					this.OnHomepageSpecialChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategorySpecial", DbType="Bit NOT NULL")]
		public bool CategorySpecial
		{
			get
			{
				return this._CategorySpecial;
			}
			set
			{
				if ((this._CategorySpecial != value))
				{
					this.OnCategorySpecialChanging(value);
					this.SendPropertyChanging();
					this._CategorySpecial = value;
					this.SendPropertyChanged("CategorySpecial");
					this.OnCategorySpecialChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InventoryDisplay", DbType="TinyInt NOT NULL")]
		public byte InventoryDisplay
		{
			get
			{
				return this._InventoryDisplay;
			}
			set
			{
				if ((this._InventoryDisplay != value))
				{
					this.OnInventoryDisplayChanging(value);
					this.SendPropertyChanging();
					this._InventoryDisplay = value;
					this.SendPropertyChanged("InventoryDisplay");
					this.OnInventoryDisplayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Keywords", DbType="NVarChar(MAX)")]
		public string Keywords
		{
			get
			{
				return this._Keywords;
			}
			set
			{
				if ((this._Keywords != value))
				{
					this.OnKeywordsChanging(value);
					this.SendPropertyChanging();
					this._Keywords = value;
					this.SendPropertyChanged("Keywords");
					this.OnKeywordsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ManufacturerID", DbType="Int")]
		public System.Nullable<int> ManufacturerID
		{
			get
			{
				return this._ManufacturerID;
			}
			set
			{
				if ((this._ManufacturerID != value))
				{
					this.OnManufacturerIDChanging(value);
					this.SendPropertyChanging();
					this._ManufacturerID = value;
					this.SendPropertyChanged("ManufacturerID");
					this.OnManufacturerIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdditionalInfoLink", DbType="NVarChar(MAX)")]
		public string AdditionalInfoLink
		{
			get
			{
				return this._AdditionalInfoLink;
			}
			set
			{
				if ((this._AdditionalInfoLink != value))
				{
					this.OnAdditionalInfoLinkChanging(value);
					this.SendPropertyChanging();
					this._AdditionalInfoLink = value;
					this.SendPropertyChanged("AdditionalInfoLink");
					this.OnAdditionalInfoLinkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdditionalInfoLinkLabel", DbType="NVarChar(MAX)")]
		public string AdditionalInfoLinkLabel
		{
			get
			{
				return this._AdditionalInfoLinkLabel;
			}
			set
			{
				if ((this._AdditionalInfoLinkLabel != value))
				{
					this.OnAdditionalInfoLinkLabelChanging(value);
					this.SendPropertyChanging();
					this._AdditionalInfoLinkLabel = value;
					this.SendPropertyChanged("AdditionalInfoLinkLabel");
					this.OnAdditionalInfoLinkLabelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShippingRuleTypeID", DbType="Int")]
		public System.Nullable<int> ShippingRuleTypeID
		{
			get
			{
				return this._ShippingRuleTypeID;
			}
			set
			{
				if ((this._ShippingRuleTypeID != value))
				{
					this.OnShippingRuleTypeIDChanging(value);
					this.SendPropertyChanging();
					this._ShippingRuleTypeID = value;
					this.SendPropertyChanged("ShippingRuleTypeID");
					this.OnShippingRuleTypeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShippingRate", DbType="Money")]
		public System.Nullable<decimal> ShippingRate
		{
			get
			{
				return this._ShippingRate;
			}
			set
			{
				if ((this._ShippingRate != value))
				{
					this.OnShippingRateChanging(value);
					this.SendPropertyChanging();
					this._ShippingRate = value;
					this.SendPropertyChanged("ShippingRate");
					this.OnShippingRateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SEOTitle", DbType="NVarChar(MAX)")]
		public string SEOTitle
		{
			get
			{
				return this._SEOTitle;
			}
			set
			{
				if ((this._SEOTitle != value))
				{
					this.OnSEOTitleChanging(value);
					this.SendPropertyChanging();
					this._SEOTitle = value;
					this.SendPropertyChanged("SEOTitle");
					this.OnSEOTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SEOKeywords", DbType="NVarChar(MAX)")]
		public string SEOKeywords
		{
			get
			{
				return this._SEOKeywords;
			}
			set
			{
				if ((this._SEOKeywords != value))
				{
					this.OnSEOKeywordsChanging(value);
					this.SendPropertyChanging();
					this._SEOKeywords = value;
					this.SendPropertyChanged("SEOKeywords");
					this.OnSEOKeywordsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SEODescription", DbType="NVarChar(MAX)")]
		public string SEODescription
		{
			get
			{
				return this._SEODescription;
			}
			set
			{
				if ((this._SEODescription != value))
				{
					this.OnSEODescriptionChanging(value);
					this.SendPropertyChanging();
					this._SEODescription = value;
					this.SendPropertyChanged("SEODescription");
					this.OnSEODescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Custom1", DbType="NVarChar(MAX)")]
		public string Custom1
		{
			get
			{
				return this._Custom1;
			}
			set
			{
				if ((this._Custom1 != value))
				{
					this.OnCustom1Changing(value);
					this.SendPropertyChanging();
					this._Custom1 = value;
					this.SendPropertyChanged("Custom1");
					this.OnCustom1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Custom2", DbType="NVarChar(MAX)")]
		public string Custom2
		{
			get
			{
				return this._Custom2;
			}
			set
			{
				if ((this._Custom2 != value))
				{
					this.OnCustom2Changing(value);
					this.SendPropertyChanging();
					this._Custom2 = value;
					this.SendPropertyChanged("Custom2");
					this.OnCustom2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Custom3", DbType="NVarChar(MAX)")]
		public string Custom3
		{
			get
			{
				return this._Custom3;
			}
			set
			{
				if ((this._Custom3 != value))
				{
					this.OnCustom3Changing(value);
					this.SendPropertyChanging();
					this._Custom3 = value;
					this.SendPropertyChanged("Custom3");
					this.OnCustom3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShipEachItemSeparately", DbType="Bit")]
		public System.Nullable<bool> ShipEachItemSeparately
		{
			get
			{
				return this._ShipEachItemSeparately;
			}
			set
			{
				if ((this._ShipEachItemSeparately != value))
				{
					this.OnShipEachItemSeparatelyChanging(value);
					this.SendPropertyChanging();
					this._ShipEachItemSeparately = value;
					this.SendPropertyChanged("ShipEachItemSeparately");
					this.OnShipEachItemSeparatelyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AllowBackOrder", DbType="Bit")]
		public System.Nullable<bool> AllowBackOrder
		{
			get
			{
				return this._AllowBackOrder;
			}
			set
			{
				if ((this._AllowBackOrder != value))
				{
					this.OnAllowBackOrderChanging(value);
					this.SendPropertyChanging();
					this._AllowBackOrder = value;
					this.SendPropertyChanged("AllowBackOrder");
					this.OnAllowBackOrderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BackOrderMsg", DbType="NVarChar(MAX)")]
		public string BackOrderMsg
		{
			get
			{
				return this._BackOrderMsg;
			}
			set
			{
				if ((this._BackOrderMsg != value))
				{
					this.OnBackOrderMsgChanging(value);
					this.SendPropertyChanging();
					this._BackOrderMsg = value;
					this.SendPropertyChanged("BackOrderMsg");
					this.OnBackOrderMsgChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DropShipInd", DbType="Bit")]
		public System.Nullable<bool> DropShipInd
		{
			get
			{
				return this._DropShipInd;
			}
			set
			{
				if ((this._DropShipInd != value))
				{
					this.OnDropShipIndChanging(value);
					this.SendPropertyChanging();
					this._DropShipInd = value;
					this.SendPropertyChanged("DropShipInd");
					this.OnDropShipIndChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DropShipEmailID", DbType="NVarChar(MAX)")]
		public string DropShipEmailID
		{
			get
			{
				return this._DropShipEmailID;
			}
			set
			{
				if ((this._DropShipEmailID != value))
				{
					this.OnDropShipEmailIDChanging(value);
					this.SendPropertyChanging();
					this._DropShipEmailID = value;
					this.SendPropertyChanged("DropShipEmailID");
					this.OnDropShipEmailIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Specifications", DbType="NVarChar(MAX)")]
		public string Specifications
		{
			get
			{
				return this._Specifications;
			}
			set
			{
				if ((this._Specifications != value))
				{
					this.OnSpecificationsChanging(value);
					this.SendPropertyChanging();
					this._Specifications = value;
					this.SendPropertyChanged("Specifications");
					this.OnSpecificationsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdditionalInformation", DbType="NVarChar(MAX)")]
		public string AdditionalInformation
		{
			get
			{
				return this._AdditionalInformation;
			}
			set
			{
				if ((this._AdditionalInformation != value))
				{
					this.OnAdditionalInformationChanging(value);
					this.SendPropertyChanging();
					this._AdditionalInformation = value;
					this.SendPropertyChanged("AdditionalInformation");
					this.OnAdditionalInformationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InStockMsg", DbType="NVarChar(MAX)")]
		public string InStockMsg
		{
			get
			{
				return this._InStockMsg;
			}
			set
			{
				if ((this._InStockMsg != value))
				{
					this.OnInStockMsgChanging(value);
					this.SendPropertyChanging();
					this._InStockMsg = value;
					this.SendPropertyChanged("InStockMsg");
					this.OnInStockMsgChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OutOfStockMsg", DbType="NVarChar(MAX)")]
		public string OutOfStockMsg
		{
			get
			{
				return this._OutOfStockMsg;
			}
			set
			{
				if ((this._OutOfStockMsg != value))
				{
					this.OnOutOfStockMsgChanging(value);
					this.SendPropertyChanging();
					this._OutOfStockMsg = value;
					this.SendPropertyChanged("OutOfStockMsg");
					this.OnOutOfStockMsgChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrackInventoryInd", DbType="Bit")]
		public System.Nullable<bool> TrackInventoryInd
		{
			get
			{
				return this._TrackInventoryInd;
			}
			set
			{
				if ((this._TrackInventoryInd != value))
				{
					this.OnTrackInventoryIndChanging(value);
					this.SendPropertyChanging();
					this._TrackInventoryInd = value;
					this.SendPropertyChanged("TrackInventoryInd");
					this.OnTrackInventoryIndChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DownloadLink", DbType="NVarChar(MAX)")]
		public string DownloadLink
		{
			get
			{
				return this._DownloadLink;
			}
			set
			{
				if ((this._DownloadLink != value))
				{
					this.OnDownloadLinkChanging(value);
					this.SendPropertyChanging();
					this._DownloadLink = value;
					this.SendPropertyChanged("DownloadLink");
					this.OnDownloadLinkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FreeShippingInd", DbType="Bit")]
		public System.Nullable<bool> FreeShippingInd
		{
			get
			{
				return this._FreeShippingInd;
			}
			set
			{
				if ((this._FreeShippingInd != value))
				{
					this.OnFreeShippingIndChanging(value);
					this.SendPropertyChanging();
					this._FreeShippingInd = value;
					this.SendPropertyChanged("FreeShippingInd");
					this.OnFreeShippingIndChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NewProductInd", DbType="Bit")]
		public System.Nullable<bool> NewProductInd
		{
			get
			{
				return this._NewProductInd;
			}
			set
			{
				if ((this._NewProductInd != value))
				{
					this.OnNewProductIndChanging(value);
					this.SendPropertyChanging();
					this._NewProductInd = value;
					this.SendPropertyChanged("NewProductInd");
					this.OnNewProductIndChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SEOURL", DbType="NVarChar(100)")]
		public string SEOURL
		{
			get
			{
				return this._SEOURL;
			}
			set
			{
				if ((this._SEOURL != value))
				{
					this.OnSEOURLChanging(value);
					this.SendPropertyChanging();
					this._SEOURL = value;
					this.SendPropertyChanged("SEOURL");
					this.OnSEOURLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaxQty", DbType="Int")]
		public System.Nullable<int> MaxQty
		{
			get
			{
				return this._MaxQty;
			}
			set
			{
				if ((this._MaxQty != value))
				{
					this.OnMaxQtyChanging(value);
					this.SendPropertyChanging();
					this._MaxQty = value;
					this.SendPropertyChanged("MaxQty");
					this.OnMaxQtyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShipSeparately", DbType="Bit NOT NULL")]
		public bool ShipSeparately
		{
			get
			{
				return this._ShipSeparately;
			}
			set
			{
				if ((this._ShipSeparately != value))
				{
					this.OnShipSeparatelyChanging(value);
					this.SendPropertyChanging();
					this._ShipSeparately = value;
					this.SendPropertyChanged("ShipSeparately");
					this.OnShipSeparatelyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FeaturedInd", DbType="Bit NOT NULL")]
		public bool FeaturedInd
		{
			get
			{
				return this._FeaturedInd;
			}
			set
			{
				if ((this._FeaturedInd != value))
				{
					this.OnFeaturedIndChanging(value);
					this.SendPropertyChanging();
					this._FeaturedInd = value;
					this.SendPropertyChanged("FeaturedInd");
					this.OnFeaturedIndChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WebServiceDownloadDte", DbType="DateTime")]
		public System.Nullable<System.DateTime> WebServiceDownloadDte
		{
			get
			{
				return this._WebServiceDownloadDte;
			}
			set
			{
				if ((this._WebServiceDownloadDte != value))
				{
					this.OnWebServiceDownloadDteChanging(value);
					this.SendPropertyChanging();
					this._WebServiceDownloadDte = value;
					this.SendPropertyChanged("WebServiceDownloadDte");
					this.OnWebServiceDownloadDteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateDte", DbType="DateTime")]
		public System.Nullable<System.DateTime> UpdateDte
		{
			get
			{
				return this._UpdateDte;
			}
			set
			{
				if ((this._UpdateDte != value))
				{
					this.OnUpdateDteChanging(value);
					this.SendPropertyChanging();
					this._UpdateDte = value;
					this.SendPropertyChanged("UpdateDte");
					this.OnUpdateDteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SupplierID", DbType="Int")]
		public System.Nullable<int> SupplierID
		{
			get
			{
				return this._SupplierID;
			}
			set
			{
				if ((this._SupplierID != value))
				{
					this.OnSupplierIDChanging(value);
					this.SendPropertyChanging();
					this._SupplierID = value;
					this.SendPropertyChanged("SupplierID");
					this.OnSupplierIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecurringBillingInd", DbType="Bit NOT NULL")]
		public bool RecurringBillingInd
		{
			get
			{
				return this._RecurringBillingInd;
			}
			set
			{
				if ((this._RecurringBillingInd != value))
				{
					this.OnRecurringBillingIndChanging(value);
					this.SendPropertyChanging();
					this._RecurringBillingInd = value;
					this.SendPropertyChanged("RecurringBillingInd");
					this.OnRecurringBillingIndChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecurringBillingInstallmentInd", DbType="Bit NOT NULL")]
		public bool RecurringBillingInstallmentInd
		{
			get
			{
				return this._RecurringBillingInstallmentInd;
			}
			set
			{
				if ((this._RecurringBillingInstallmentInd != value))
				{
					this.OnRecurringBillingInstallmentIndChanging(value);
					this.SendPropertyChanging();
					this._RecurringBillingInstallmentInd = value;
					this.SendPropertyChanged("RecurringBillingInstallmentInd");
					this.OnRecurringBillingInstallmentIndChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecurringBillingPeriod", DbType="NVarChar(50)")]
		public string RecurringBillingPeriod
		{
			get
			{
				return this._RecurringBillingPeriod;
			}
			set
			{
				if ((this._RecurringBillingPeriod != value))
				{
					this.OnRecurringBillingPeriodChanging(value);
					this.SendPropertyChanging();
					this._RecurringBillingPeriod = value;
					this.SendPropertyChanged("RecurringBillingPeriod");
					this.OnRecurringBillingPeriodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecurringBillingFrequency", DbType="NVarChar(MAX)")]
		public string RecurringBillingFrequency
		{
			get
			{
				return this._RecurringBillingFrequency;
			}
			set
			{
				if ((this._RecurringBillingFrequency != value))
				{
					this.OnRecurringBillingFrequencyChanging(value);
					this.SendPropertyChanging();
					this._RecurringBillingFrequency = value;
					this.SendPropertyChanged("RecurringBillingFrequency");
					this.OnRecurringBillingFrequencyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecurringBillingTotalCycles", DbType="Int")]
		public System.Nullable<int> RecurringBillingTotalCycles
		{
			get
			{
				return this._RecurringBillingTotalCycles;
			}
			set
			{
				if ((this._RecurringBillingTotalCycles != value))
				{
					this.OnRecurringBillingTotalCyclesChanging(value);
					this.SendPropertyChanging();
					this._RecurringBillingTotalCycles = value;
					this.SendPropertyChanged("RecurringBillingTotalCycles");
					this.OnRecurringBillingTotalCyclesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecurringBillingInitialAmount", DbType="Money")]
		public System.Nullable<decimal> RecurringBillingInitialAmount
		{
			get
			{
				return this._RecurringBillingInitialAmount;
			}
			set
			{
				if ((this._RecurringBillingInitialAmount != value))
				{
					this.OnRecurringBillingInitialAmountChanging(value);
					this.SendPropertyChanging();
					this._RecurringBillingInitialAmount = value;
					this.SendPropertyChanged("RecurringBillingInitialAmount");
					this.OnRecurringBillingInitialAmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaxClassID", DbType="Int")]
		public System.Nullable<int> TaxClassID
		{
			get
			{
				return this._TaxClassID;
			}
			set
			{
				if ((this._TaxClassID != value))
				{
					this.OnTaxClassIDChanging(value);
					this.SendPropertyChanging();
					this._TaxClassID = value;
					this.SendPropertyChanged("TaxClassID");
					this.OnTaxClassIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MinQty", DbType="Int")]
		public System.Nullable<int> MinQty
		{
			get
			{
				return this._MinQty;
			}
			set
			{
				if ((this._MinQty != value))
				{
					this.OnMinQtyChanging(value);
					this.SendPropertyChanging();
					this._MinQty = value;
					this.SendPropertyChanged("MinQty");
					this.OnMinQtyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReviewStateID", DbType="Int")]
		public System.Nullable<int> ReviewStateID
		{
			get
			{
				return this._ReviewStateID;
			}
			set
			{
				if ((this._ReviewStateID != value))
				{
					this.OnReviewStateIDChanging(value);
					this.SendPropertyChanging();
					this._ReviewStateID = value;
					this.SendPropertyChanged("ReviewStateID");
					this.OnReviewStateIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AffiliateUrl", DbType="VarChar(512)")]
		public string AffiliateUrl
		{
			get
			{
				return this._AffiliateUrl;
			}
			set
			{
				if ((this._AffiliateUrl != value))
				{
					this.OnAffiliateUrlChanging(value);
					this.SendPropertyChanging();
					this._AffiliateUrl = value;
					this.SendPropertyChanged("AffiliateUrl");
					this.OnAffiliateUrlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsShippable", DbType="Bit")]
		public System.Nullable<bool> IsShippable
		{
			get
			{
				return this._IsShippable;
			}
			set
			{
				if ((this._IsShippable != value))
				{
					this.OnIsShippableChanging(value);
					this.SendPropertyChanging();
					this._IsShippable = value;
					this.SendPropertyChanged("IsShippable");
					this.OnIsShippableChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountID", DbType="Int")]
		public System.Nullable<int> AccountID
		{
			get
			{
				return this._AccountID;
			}
			set
			{
				if ((this._AccountID != value))
				{
					this.OnAccountIDChanging(value);
					this.SendPropertyChanging();
					this._AccountID = value;
					this.SendPropertyChanged("AccountID");
					this.OnAccountIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PortalID", DbType="Int")]
		public System.Nullable<int> PortalID
		{
			get
			{
				return this._PortalID;
			}
			set
			{
				if ((this._PortalID != value))
				{
					this.OnPortalIDChanging(value);
					this.SendPropertyChanging();
					this._PortalID = value;
					this.SendPropertyChanged("PortalID");
					this.OnPortalIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Franchisable", DbType="Bit NOT NULL")]
		public bool Franchisable
		{
			get
			{
				return this._Franchisable;
			}
			set
			{
				if ((this._Franchisable != value))
				{
					this.OnFranchisableChanging(value);
					this.SendPropertyChanging();
					this._Franchisable = value;
					this.SendPropertyChanged("Franchisable");
					this.OnFranchisableChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
